LOCAL_PATH := $(call my-dir)

ifneq ($(filter redfin, $(TARGET_DEVICE)),)

# F-Droid Version Latest (2020-10-29)
include $(CLEAR_VARS)
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE := fdroid
LOCAL_MODULE_TAGS := optional
LOCAL_BUILT_MODULE_STEM := package.apk
LOCAL_SYSTEM_EXT_MODULE := true
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MODULE_OWNER := pixelmod
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := $(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := platform
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

endif
